---

- name: Configure /etc/krb5.conf
  template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  become: yes
  when: sssd_configure_kerberos
