---

- include_tasks: dns_hosts.yml
  when: remove_servers_from_etc_hosts

- include_tasks: dns_query.yml
  when: sssd_test_dns

- include_tasks: dns_test.yml
  when: sssd_test_dns

- include_tasks: apt.yml
  when: sssd_install_sssd_tools

- include_tasks: kerberos.yml
  when: sssd_configure_kerberos

- include_tasks: ldap.yml
  when: sssd_configure_ldap

- include_tasks: ipa.yml
  when: sssd_configure_ipa

- include_tasks: sssd.yml
