---

- name: Configure /etc/sssd/sssd.conf
  template:
    src: templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
  become: yes
  when: sssd_configure_sssd_conf

- name: Check /etc/sssd/sssd.conf
  command: sssctl config-check
  become: yes
  register: sssd_config_check_result
  changed_when: False

- name: Debug sssd_config_check_result
  debug:
    var: sssd_config_check_result
    verbosity: 2
  changed_when: False

- name: Restart sssd
  service:
    name: sssd
    state: restarted
  become: yes
  when: not sssd_config_check_result.failed

- name: waiting backend
  pause:
    seconds: "{{ sssd_waiting_after_restart }}"

- name: Verify domain status
  command: "sssctl domain-status {{ ipa_domain }}"
  become: yes
  register: sssd_config_domain_status_result
  changed_when: False

- name: Debug sssd_config_domain_status_result
  debug:
    var: sssd_config_domain_status_result.stdout_lines
    verbosity: 2
  changed_when: False

- name: Verify Online status
  fail:
    msg: 'Online status is Offline'
  when: "'Online status: Offline' in sssd_config_domain_status_result.stdout_lines"
