---

sssd_configure_service: false

sssd_conf_service:
  timeout: "{{ default_service_timeout }}"
  debug: "{{ default_debug }}"
  debug_level: "{{ default_debug_level }}"
  debug_timestamps: "{{ default_debug_timestamps }}"
  debug_microseconds: "{{ default_debug_microseconds }}"
  debug_to_files: "{{ default_debug_to_files }}"
  command: false
  reconnection_retries: false
  fd_limit: false
  client_idle_timeout: false
  responder_idle_timeout: false
  cache_first: false
  description: false
